name: incremental_dom_facade
description: Dart library for Incremental DOM
version: 0.0.1
author: Kulshekhar Kabra <kulshekhar+dart@gmail.com>
homepage: https://github.com/kulshekhar/incremental_dom

environment:
  sdk: '>=1.0.0 <2.0.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
